require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CatsController, type: :controller do

  describe "anonymous user" do
    before :each do
      # This simulates an anonymous user
      login_with nil
    end
    it "should be redirected to signin" do
      get :index
      expect( response ).to redirect_to( new_user_session_path )
    end
  end
  
  describe "signed in user" do
    before :each do
      login_with create( :user )
    end
    it "should let a user see cat fight" do
      get :fight
      expect( response ).to render_template( :fight )
    end

    it "should let user see top cats" do
      get :top
      expect( response ).to render_template( :top )
    end

    it "should not let user to see index" do
      get :index
      expect( response ).to redirect_to( fight_cats_path )
    end
  end
  
  describe "signed in as admin" do
    it "should allow admins to see index" do
      login_with create( :admin )
      get :index
      expect( response ).to render_template( :index )
    end
  end

  # # This should return the minimal set of attributes required to create a valid
  # # cat. As you add validations to cat, be sure to
  # # adjust the attributes here as well.
  # let(:valid_attributes) {
  #   skip("Add a hash of attributes valid for your model")
  # }

  # let(:invalid_attributes) {
  #   skip("Add a hash of attributes invalid for your model")
  # }

  # # This should return the minimal set of values that should be in the session
  # # in order to pass any filters (e.g. authentication) defined in
  # # catsController. Be sure to keep this updated too.
  # let(:valid_session) { {} }

  # describe "GET #index" do
  #   it "assigns all cats as @cats" do
  #     cat = cat.create! valid_attributes
  #     get :index, {}, valid_session
  #     expect(assigns(:cats)).to eq([cat])
  #   end
  # end

  # describe "GET #show" do
  #   it "assigns the requested cat as @cat" do
  #     cat = cat.create! valid_attributes
  #     get :show, {:id => cat.to_param}, valid_session
  #     expect(assigns(:cat)).to eq(cat)
  #   end
  # end

  # describe "GET #new" do
  #   it "assigns a new cat as @cat" do
  #     get :new, {}, valid_session
  #     expect(assigns(:cat)).to be_a_new(cat)
  #   end
  # end

  # describe "GET #edit" do
  #   it "assigns the requested cat as @cat" do
  #     cat = cat.create! valid_attributes
  #     get :edit, {:id => cat.to_param}, valid_session
  #     expect(assigns(:cat)).to eq(cat)
  #   end
  # end

  # describe "POST #create" do
  #   context "with valid params" do
  #     it "creates a new cat" do
  #       expect {
  #         post :create, {:cat => valid_attributes}, valid_session
  #       }.to change(cat, :count).by(1)
  #     end

  #     it "assigns a newly created cat as @cat" do
  #       post :create, {:cat => valid_attributes}, valid_session
  #       expect(assigns(:cat)).to be_a(cat)
  #       expect(assigns(:cat)).to be_persisted
  #     end

  #     it "redirects to the created cat" do
  #       post :create, {:cat => valid_attributes}, valid_session
  #       expect(response).to redirect_to(cat.last)
  #     end
  #   end

  #   context "with invalid params" do
  #     it "assigns a newly created but unsaved cat as @cat" do
  #       post :create, {:cat => invalid_attributes}, valid_session
  #       expect(assigns(:cat)).to be_a_new(cat)
  #     end

  #     it "re-renders the 'new' template" do
  #       post :create, {:cat => invalid_attributes}, valid_session
  #       expect(response).to render_template("new")
  #     end
  #   end
  # end

  # describe "PUT #update" do
  #   context "with valid params" do
  #     let(:new_attributes) {
  #       skip("Add a hash of attributes valid for your model")
  #     }

  #     it "updates the requested cat" do
  #       cat = cat.create! valid_attributes
  #       put :update, {:id => cat.to_param, :cat => new_attributes}, valid_session
  #       cat.reload
  #       skip("Add assertions for updated state")
  #     end

  #     it "assigns the requested cat as @cat" do
  #       cat = cat.create! valid_attributes
  #       put :update, {:id => cat.to_param, :cat => valid_attributes}, valid_session
  #       expect(assigns(:cat)).to eq(cat)
  #     end

  #     it "redirects to the cat" do
  #       cat = cat.create! valid_attributes
  #       put :update, {:id => cat.to_param, :cat => valid_attributes}, valid_session
  #       expect(response).to redirect_to(cat)
  #     end
  #   end

  #   context "with invalid params" do
  #     it "assigns the cat as @cat" do
  #       cat = cat.create! valid_attributes
  #       put :update, {:id => cat.to_param, :cat => invalid_attributes}, valid_session
  #       expect(assigns(:cat)).to eq(cat)
  #     end

  #     it "re-renders the 'edit' template" do
  #       cat = cat.create! valid_attributes
  #       put :update, {:id => cat.to_param, :cat => invalid_attributes}, valid_session
  #       expect(response).to render_template("edit")
  #     end
  #   end
  # end

  # describe "DELETE #destroy" do
  #   it "destroys the requested cat" do
  #     cat = cat.create! valid_attributes
  #     expect {
  #       delete :destroy, {:id => cat.to_param}, valid_session
  #     }.to change(cat, :count).by(-1)
  #   end

  #   it "redirects to the cats list" do
  #     cat = cat.create! valid_attributes
  #     delete :destroy, {:id => cat.to_param}, valid_session
  #     expect(response).to redirect_to(cats_url)
  #   end
  # end

end
